export default {
	dictionaries: [
		'en_US',
		'de-de',
		'softwareTerms',
		'typescript',
		'node',
		'html',
		'css',
		'bash',
		'misc',
		'somehow-digital',
	],
	ignorePaths: [
		'node_modules/',
		'.git/',
		'.husky/',
		'.idea/',
		'package.json',
		'pnpm-lock.yaml',
		'.npmrc',
		'.nvmrc',
		'.gitignore',
		'.gitattributes',
		'.editorconfig',
		'.prettierignore',
	],
	import: ['@cspell/dict-de-de', './dictionary/cspell-ext.json'],
	language: 'en',
	version: '0.2',
};
