name: RELEASE NEW

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  source:
    name: verify source
    uses: ./.github/workflows/source.yaml
  release:
    name: release version
    runs-on: ubuntu-latest
    needs: [source]
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          config-file: release-please-config.json
