name: RELEASE NEW

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  source:
    name: verify source
    uses: ./.github/workflows/source.yaml
  release:
    name: release version
    runs-on: ubuntu-latest
    needs: [source]
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
